apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: {{ include "store-chart.name" . }}
    tier: mysql
  clusterIP: None # This makes it a "Headless Service," perfect for databases 