apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.db.rootPassword }}
  mysql-database: {{ .Values.db.name }}