apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-chart.fullname" . }}-wordpress
spec:
  selector:
    matchLabels:
      app: {{ include "store-chart.name" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ include "store-chart.name" . }}
        tier: frontend
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: mysql-root-password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: mysql-database
          ports:
            - containerPort: 80
              name: wordpress