apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-chart.fullname" . }}-wordpress
spec:
  ports:
    - port: 80
  selector:
    app: {{ include "store-chart.name" . }}
    tier: frontend
  type: ClusterIP